export const ACTION_TYPE = {
    FETCH_MOVIES_START: "FETCH_MOVIES",
    FETCH_MOVIES_SUCCESS: "FETCH_MOVIES_SUCCESS",
    FETCH_MOVIES_ERROR: "FETCH_MOVIES_ERROR",
    FETCH_ACTORS_START: "FETCH_ACTORS_START",
    FETCH_ACTORS_SUCCESS: "FETCH_ACTORS_SUCCESS",
    FETCH_ACTORS_ERROR: "FETCH_ACTORS_ERROR"
}
